version: "3.8"
services:
  server:
    build: ./server
    container_name: server_container
    ports:
      - "5000:5000"

    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"

    volumes:
      - ./client:/app
      - /app/node_modules

    stdin_open: true
    tty: true # for starting the container in interactive mode (opposite of detached mode)
